apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: jenkins
  name: gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: http
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: jenkins
  name: jenkins
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: jenkins-np.jenkins.svc.cluster.local
        port:
          number: 80
